// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BlissOwen
Rcpp::List BlissOwen(Rcpp::NumericVector y);
RcppExport SEXP _fitgen_BlissOwen(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(BlissOwen(y));
    return rcpp_result_gen;
END_RCPP
}
// CommonBlissOwen
Rcpp::List CommonBlissOwen(Rcpp::NumericMatrix y, int maxit, double tol, double posthres);
RcppExport SEXP _fitgen_CommonBlissOwen(SEXP ySEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP posthresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type posthres(posthresSEXP);
    rcpp_result_gen = Rcpp::wrap(CommonBlissOwen(y, maxit, tol, posthres));
    return rcpp_result_gen;
END_RCPP
}
// GroupedCommonBlissOwen
Rcpp::List GroupedCommonBlissOwen(Rcpp::NumericMatrix y, int maxit, double tol, double tolphi, double posthres, int down_ndev, int up_ndev, double down_maxprop, double up_maxprop, int niter);
RcppExport SEXP _fitgen_GroupedCommonBlissOwen(SEXP ySEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP tolphiSEXP, SEXP posthresSEXP, SEXP down_ndevSEXP, SEXP up_ndevSEXP, SEXP down_maxpropSEXP, SEXP up_maxpropSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type tolphi(tolphiSEXP);
    Rcpp::traits::input_parameter< double >::type posthres(posthresSEXP);
    Rcpp::traits::input_parameter< int >::type down_ndev(down_ndevSEXP);
    Rcpp::traits::input_parameter< int >::type up_ndev(up_ndevSEXP);
    Rcpp::traits::input_parameter< double >::type down_maxprop(down_maxpropSEXP);
    Rcpp::traits::input_parameter< double >::type up_maxprop(up_maxpropSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(GroupedCommonBlissOwen(y, maxit, tol, tolphi, posthres, down_ndev, up_ndev, down_maxprop, up_maxprop, niter));
    return rcpp_result_gen;
END_RCPP
}
// FitGenSetDebug
void FitGenSetDebug(bool deb, bool lldeb);
RcppExport SEXP _fitgen_FitGenSetDebug(SEXP debSEXP, SEXP lldebSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type deb(debSEXP);
    Rcpp::traits::input_parameter< bool >::type lldeb(lldebSEXP);
    FitGenSetDebug(deb, lldeb);
    return R_NilValue;
END_RCPP
}
// FitGenGetDebug
bool FitGenGetDebug();
RcppExport SEXP _fitgen_FitGenGetDebug() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(FitGenGetDebug());
    return rcpp_result_gen;
END_RCPP
}
// FitRowGLM
Rcpp::List FitRowGLM(const Rcpp::NumericMatrix dat, int ng, std::string model, const Rcpp::NumericMatrix commonX, const Rcpp::NumericVector offset, double Phi, bool retmu);
RcppExport SEXP _fitgen_FitRowGLM(SEXP datSEXP, SEXP ngSEXP, SEXP modelSEXP, SEXP commonXSEXP, SEXP offsetSEXP, SEXP PhiSEXP, SEXP retmuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type ng(ngSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type commonX(commonXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< bool >::type retmu(retmuSEXP);
    rcpp_result_gen = Rcpp::wrap(FitRowGLM(dat, ng, model, commonX, offset, Phi, retmu));
    return rcpp_result_gen;
END_RCPP
}
// FitExtendedRowGLM
Rcpp::List FitExtendedRowGLM(const Rcpp::NumericMatrix dat, const Rcpp::IntegerMatrix Cl, int ng, std::string model, const Rcpp::NumericMatrix commonX, const Rcpp::NumericVector offset, double Phi, bool retmu);
RcppExport SEXP _fitgen_FitExtendedRowGLM(SEXP datSEXP, SEXP ClSEXP, SEXP ngSEXP, SEXP modelSEXP, SEXP commonXSEXP, SEXP offsetSEXP, SEXP PhiSEXP, SEXP retmuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix >::type Cl(ClSEXP);
    Rcpp::traits::input_parameter< int >::type ng(ngSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type commonX(commonXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< bool >::type retmu(retmuSEXP);
    rcpp_result_gen = Rcpp::wrap(FitExtendedRowGLM(dat, Cl, ng, model, commonX, offset, Phi, retmu));
    return rcpp_result_gen;
END_RCPP
}
// FitGLMWithNei
Rcpp::List FitGLMWithNei(const Rcpp::NumericMatrix dat, bool normalized, const Rcpp::IntegerMatrix Cl, std::string model, const Rcpp::LogicalVector selected, const Rcpp::NumericMatrix commonX, std::string Phi_estproc, Rcpp::NumericVector Phi_external, bool retmu);
RcppExport SEXP _fitgen_FitGLMWithNei(SEXP datSEXP, SEXP normalizedSEXP, SEXP ClSEXP, SEXP modelSEXP, SEXP selectedSEXP, SEXP commonXSEXP, SEXP Phi_estprocSEXP, SEXP Phi_externalSEXP, SEXP retmuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< bool >::type normalized(normalizedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix >::type Cl(ClSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector >::type selected(selectedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type commonX(commonXSEXP);
    Rcpp::traits::input_parameter< std::string >::type Phi_estproc(Phi_estprocSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Phi_external(Phi_externalSEXP);
    Rcpp::traits::input_parameter< bool >::type retmu(retmuSEXP);
    rcpp_result_gen = Rcpp::wrap(FitGLMWithNei(dat, normalized, Cl, model, selected, commonX, Phi_estproc, Phi_external, retmu));
    return rcpp_result_gen;
END_RCPP
}
// FitGLMInd
Rcpp::List FitGLMInd(const Rcpp::NumericMatrix dat, bool normalized, std::string model, const Rcpp::LogicalVector selected, const Rcpp::NumericMatrix commonX, std::string Phi_estproc, Rcpp::NumericVector Phi_external, bool retmu);
RcppExport SEXP _fitgen_FitGLMInd(SEXP datSEXP, SEXP normalizedSEXP, SEXP modelSEXP, SEXP selectedSEXP, SEXP commonXSEXP, SEXP Phi_estprocSEXP, SEXP Phi_externalSEXP, SEXP retmuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< bool >::type normalized(normalizedSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector >::type selected(selectedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type commonX(commonXSEXP);
    Rcpp::traits::input_parameter< std::string >::type Phi_estproc(Phi_estprocSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Phi_external(Phi_externalSEXP);
    Rcpp::traits::input_parameter< bool >::type retmu(retmuSEXP);
    rcpp_result_gen = Rcpp::wrap(FitGLMInd(dat, normalized, model, selected, commonX, Phi_estproc, Phi_external, retmu));
    return rcpp_result_gen;
END_RCPP
}
// SolveLinearSystem
Rcpp::NumericVector SolveLinearSystem(Rcpp::NumericMatrix& A, const Rcpp::NumericVector& b, double tol);
RcppExport SEXP _fitgen_SolveLinearSystem(SEXP ASEXP, SEXP bSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(SolveLinearSystem(A, b, tol));
    return rcpp_result_gen;
END_RCPP
}
// SolveLinearSystemWithInverse
Rcpp::List SolveLinearSystemWithInverse(Rcpp::NumericMatrix& A, const Rcpp::NumericVector& b, double tol);
RcppExport SEXP _fitgen_SolveLinearSystemWithInverse(SEXP ASEXP, SEXP bSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(SolveLinearSystemWithInverse(A, b, tol));
    return rcpp_result_gen;
END_RCPP
}
// QRdec
Rcpp::List QRdec(Rcpp::NumericMatrix& A, double tol);
RcppExport SEXP _fitgen_QRdec(SEXP ASEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(QRdec(A, tol));
    return rcpp_result_gen;
END_RCPP
}
// StGLM
Rcpp::List StGLM(Rcpp::NumericVector y, Rcpp::NumericMatrix X, std::string model, Rcpp::NumericVector offset, bool warn_me, double Phi, bool retmu);
RcppExport SEXP _fitgen_StGLM(SEXP ySEXP, SEXP XSEXP, SEXP modelSEXP, SEXP offsetSEXP, SEXP warn_meSEXP, SEXP PhiSEXP, SEXP retmuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< bool >::type warn_me(warn_meSEXP);
    Rcpp::traits::input_parameter< double >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< bool >::type retmu(retmuSEXP);
    rcpp_result_gen = Rcpp::wrap(StGLM(y, X, model, offset, warn_me, Phi, retmu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fitgen_BlissOwen", (DL_FUNC) &_fitgen_BlissOwen, 1},
    {"_fitgen_CommonBlissOwen", (DL_FUNC) &_fitgen_CommonBlissOwen, 4},
    {"_fitgen_GroupedCommonBlissOwen", (DL_FUNC) &_fitgen_GroupedCommonBlissOwen, 10},
    {"_fitgen_FitGenSetDebug", (DL_FUNC) &_fitgen_FitGenSetDebug, 2},
    {"_fitgen_FitGenGetDebug", (DL_FUNC) &_fitgen_FitGenGetDebug, 0},
    {"_fitgen_FitRowGLM", (DL_FUNC) &_fitgen_FitRowGLM, 7},
    {"_fitgen_FitExtendedRowGLM", (DL_FUNC) &_fitgen_FitExtendedRowGLM, 8},
    {"_fitgen_FitGLMWithNei", (DL_FUNC) &_fitgen_FitGLMWithNei, 9},
    {"_fitgen_FitGLMInd", (DL_FUNC) &_fitgen_FitGLMInd, 8},
    {"_fitgen_SolveLinearSystem", (DL_FUNC) &_fitgen_SolveLinearSystem, 3},
    {"_fitgen_SolveLinearSystemWithInverse", (DL_FUNC) &_fitgen_SolveLinearSystemWithInverse, 3},
    {"_fitgen_QRdec", (DL_FUNC) &_fitgen_QRdec, 2},
    {"_fitgen_StGLM", (DL_FUNC) &_fitgen_StGLM, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_fitgen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
