# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' BlissOwen
#'
#' Gets a vector of p observations assuming they come from a negative binomial distribution with overdispersion
#' parameter Phi (var=mu+Phi*mu^2) and uses the Bliss-Owen method to get an estimator for Phi
#'
#' @param  y					A vector of observations, size p
#' @return VPhi["Phi","valid"] A list with a real value, the Bliss-Owen estimation for the overdispersion parameter, and a 
#' boolean mark to indicate if the estimation is considered valid. It will not be when statistics u, v or both are negative or null.
#' @examples
#' n = 200
#' mu = 30
#' size = .7
#' y = rnbinom(n = n, size = size, mu= mu)
#' phi_est = BlissOwen(y)
#' @export 
BlissOwen <- function(y) {
    .Call('_fitgen_BlissOwen', PACKAGE = 'fitgen', y)
}

#' CommonBlissOwen
#'
#' Gets a matrix of n samples of p observations each given as a nxp matrix (one sample per row) and, assuming that all 
#' of them come from a negative binomial ditribution with a common overdispersion Phi value (var=mu+Phi*mu^2), uses
#' the Bliss-Owen method to get a common estimator for Phi using all the samples for which estimation is possible.
#' These samples are marked as true in an array of boolean values which is returned. Estimation is considered impossible
#' if the v-statistic (s^2-mu) is lower or equal than a threshold (0 by default). 
#' 
#' When estimation is possible, the method proceeds iteratively until either the difference of estimated values between
#' successive iterations is below the tolerance or until the fixed number of iterations has been reached.
#'
#' @param  y		 A matrix of sample, size n x p
#' @param  maxit	 Maximum number of allowed iterations. Default: 100
#' @param  tol      Tolerance to exit if change is below its value. Default: 1e-9
#' @param  posthres Threhold to consider a sample valid if its v-value is strictly above it. Default: 0.0
#' @return VPhi["Phi","valid"] A list of two element, a real number with the Phi estimated value and a  boolean array with length=nrows(y).
#' @examples
#' n = 100
#' N = 400
#' mu = 1:N
#' size = .7
#' y = t(sapply(mu,function(i) rnbinom(n = n, size = size, mu= i)))
#' VPhi=CommonBlissOwen(y)
#' cat("Estimated value: ",VPhi$Phi," using ",sum(VPhi$valid)," of all the samples.\n")
#' @export
CommonBlissOwen <- function(y, maxit = 100L, tol = 1e-9, posthres = 0.0) {
    .Call('_fitgen_CommonBlissOwen', PACKAGE = 'fitgen', y, maxit, tol, posthres)
}

#' GroupedCommonBlissOwen
#'
#' 
#' Gets a matrix of n samples of p observations each given as a nxp matrix (one sample per row) and, assuming that all 
#' of them come from several negative binomial ditributions, each with a different overdispersion Phi value
#' (var_i = mu_i+Phi_i*mu_i^2), uses the Bliss-Owen method to get estimations for the different Phi values when they
#' can be estimated (which is determined by the fact that its v-statistic is strictly above a threshold, 0 by default).
#' 
#' The estimation of each Phi proceeds by estimating first the value for each row with the simple BlissOwen method and
#' then, grouping for each sample all the others whose absolute value of difference of Phi is less than the tolerance and
#' using them to estimate the value through the same method used in the CommonBlissOwen function programmed in this package.\cr
#' The default value for tolphi, which is -1.0, does not mean -1 (which would make no sense) but a mark to indicate that\cr
#' it must be estimated using from formula (5) of BlissOwen[58], which depends on the sample. If you set any other value\cr
#' for tolphi that value will be used for all rows instead of individually estimating the tolerance for each sample.
#'
#' @param  y		A matrix of samples, size n x p
#' @param  maxit	Maximum number of allowed iterations for each Phi estimation. Default: 100 
#' @param  tol     Tolerance to exit if change in each Phi estimation is below its value. Default: 1e-9
#' @param  tolphi  Maximum absolute difference in Phi value to be part of the estimation around a given sample. Default: -1.0, which means 'Estimate from the sample'
#' @param  posthres Threshold to consider a sample valid if its v-value is strictly above it. Default: 0.0
#' @param  down_ndev Integer with the number of stdev to limit interval of grouping by the lower side. Default: 3
#' @param  up_ndev Integer with the number of stdev to limit interval of grouping by the upper side. Default: 2
#' @param  down_maxprop Maximum proportion of the total samples that, being in the interval [mean-down_ndev*stdev,mean], must be considered. Default: 1.0 (consider all the samples that fall in the interval)
#' @param  up_maxprop Maximum proportion of the total samples that, being in the interval [mean,mean+up_ndev*stdev], must be considered. Default: 1.0 (consider all the samples that fall in the interval)
#' @param  niter   Integer with the number of iteration smoothing steps. Default: 2
#' @return A list L of n lists, each one (i.e.: L[[row]]) with the following keys:
#' \itemize{
#'           \item Phi    - A numeric value with the estimated Phi value for L[[row]]
#'           \item valid  - A boolean indicating if row has been kept or discarded according to the v-threshold criterion
#'           \item nsel   - An integer indicating how many samples were selected to be averaged with the sample at this row
#'           \item tolphi - A numeric value with the estimated tolerance for sample grouping for this row
#' }
#' If L[[i]]$valid is false the values of L[[i]]$Phi$ and of L[[i]]$tolphi will be NaN and the value of L[[i]]$nsel will be 0.
#' @examples
#' n = 50
#' size = seq(.2,2,length.out=5)
#' mu = 30
#' y = t(sapply(size,function(i) rnbinom(n = n, size = i, mu= mu)))
#' VPhi=GroupedCommonBlissOwen(y)
#' @export
GroupedCommonBlissOwen <- function(y, maxit = 100L, tol = 1e-9, tolphi = -1.0, posthres = 0.0, down_ndev = 3L, up_ndev = 2L, down_maxprop = 1.0, up_maxprop = 1.0, niter = 2L) {
    .Call('_fitgen_GroupedCommonBlissOwen', PACKAGE = 'fitgen', y, maxit, tol, tolphi, posthres, down_ndev, up_ndev, down_maxprop, up_maxprop, niter)
}

#' FitGenSetDebug
#' 
#' Sets debugging in fitgen package to ON (with TRUE) or OFF (with FALSE) or even sets\cr
#' a lower level of debug to see inside the numerical algorithms.\cr
#' On package load the default status of both debugging levels is OFF.\cr
#' Setting any debug level to ON shows a message. Setting to OFF does not show anything (since debugging is OFF...)
#'
#' @param deb   boolean, TRUE to generate normal debug messages and FALSE to turn them off.
#' @param lldeb boolean, TRUE to generate low level debug messages (very verbose) and FALSE to turn them off. Setting this parameter
#' to TRUE sets also deb to TRUE. Default: FALSE
#' @return      No return value, called for side effects (internal boolean flag changed)
#' @examples
#' FitGenSetDebug(TRUE)
#' FitGenSetDebug(FALSE)
#' FitGenSetDebug(TRUE,TRUE)
#' FitGenSetDebug(TRUE,FALSE)
#' @export
FitGenSetDebug <- function(deb, lldeb = FALSE) {
    invisible(.Call('_fitgen_FitGenSetDebug', PACKAGE = 'fitgen', deb, lldeb))
}

#' FitGenGetDebug
#' Returns the current value of the debug flag (TRUE or FALSE).\cr
#' Used by the R functions of the package to know if they should emit messages or not.
#'
#' @return Boolean value with the current value of the internal DEB flag.
#' @examples
#' if (FitGenGetDebug()) {
#'  cat("This is a message emitted because we are in debug mode.\n")
#' }
#' @export
FitGenGetDebug <- function() {
    .Call('_fitgen_FitGenGetDebug', PACKAGE = 'fitgen')
}

#' FitRowGLM
#' 
#' Fits a Poisson or General Linear Model to the requested row of a data matrix using as predictors
#' those included in the commonX model matrix
#'
#' Error management: This function manages the errors in the same way as StGLM, i.e.: it returns an emtpy vector for beta,
#' the value 0 for X2, sums and Dev and the empty matrix for CovM if the model is numerically unstable. This MUST be checked
#' by the caller function and it is to allow it to call a different model if the current one cannot be fitted
#'
#' @param    dat     Numeric matrix of counts with n individuals/genes as rows and c studies/cases as columns
#' @param    ng      Number of the individual/gene for which the model must be adjusted
#' @param    model   A string with the model to fit, either "poisson","binlogit","negbin" or "binlogitw"
#' @param    commonX Model matrix with c rows and with the columns common to all individuals/genes. Usually generated as model.matrix(...)
#' @param    offset  Numeric vector with offsets for the GLM. Its length must be the number of colums of the counts matrix, i.e. c. If the data are normalized this vector should be passed filled with 0.
#' @param    Phi     Estimated value for Phi in the case of negative binomial model. It can't be 0.
#' @param    retmu   Boolean to indicate whether or not the vector of estimated means must be returned. Default: FALSE
#' @return   A list with the following keys:
#' \itemize{
#' \item model - A string with the model used to adjust. A copy of the model parameter, useful to keep track of it when the result is included in a list 
#' \item beta  - A numeric vector with the value of the model parameters assuming the requested distribution
#' \item muest - A numeric vector with the estimated means or NULL if parameter retmu was FALSE
#' \item X2    - The numeric value of the X2 statistic (see help of StGLM)
#' \item sums  - The numeric value of the sums statistic (see help of StGLM)
#' \item Dev   - The numeric value of the deviance of the model
#' \item CovM  - Covariance matrix of the maximum likelihood estimator of the model coefficients
#' }
#' @examples
#' # To be done
#' @export
FitRowGLM <- function(dat, ng, model, commonX, offset, Phi = 0.0, retmu = FALSE) {
    .Call('_fitgen_FitRowGLM', PACKAGE = 'fitgen', dat, ng, model, commonX, offset, Phi, retmu)
}

#' FitExtendedRowGLM
#' 
#' Fits a Poisson or Negative Binomial General Linear Model to the requested row of a data matrix using as predictors
#' those included in the commonX model matrix plus the columns of those rows in the data matrix which are neighbours of the current row.\cr
#' The concept of neighbourhood is encoded in a nxp matrix of closeness which contains int its i-th row\cr
#' the index of the p cases which are closest to the i-th case. The dimension of the matrix is used, so p is not explicitly passed as parameter.
#'
#' @param    dat     Numeric matrix of counts with n individuals/genes as rows and c studies/cases as columns
#' @param    Cl      Numeric matrix of affinity with n individuals/genes as rows and the integer indexes of the p closest individuals in its p columns
#' @param    ng      Number of the individual/gene for which the complete model matrix has to be built
#' @param    model   A string with the model to fit, either "poisson", "binlogit", "negbin" or "binlogitw"
#' @param    commonX Partial model matrix with c rows and with the columns common to all individuals/genes. Usually generated as model.matrix(...)
#' @param    offset  Numeric vector with offsets for the GLM. Its length must be the number of colums of the counts matrix, i.e. c. If the data are normalized this vector should be passed filled with 0.
#' @param    Phi     Estimated value for Phi in the case of negative binomial model. It can't be 0.
#' @param    retmu   Boolean to indicate whether or not the vector of estimated means must be returned
#' @return   A list with the following keys:
#' \itemize{
#' \item model  - A string with the model used to adjust. A copy of the model parameter, useful to keep track of it when the result is included in a list 
#' \item beta   - A numeric vector with the value of the model parameters assuming the requested distribution
#' \item muest  - A numeric vector with the estimated means or NULL if parameter retmu was FALSE
#' \item X2     - The numeric value of the X2 statistic (see help of StGLM)
#' \item sums   - The numeric value of the sums statistic (see help of StGLM)
#' \item numnei - The number of neighbours that has been used to obtain a valid fit, either p or a lower value
#' \item Dev    - The numeric value of the deviance of the model
#' \item CovM   - Covariance matrix of the maximum likelihood estimator of the model coefficients
#' }
#' @examples
#' # To be done
#' @export
FitExtendedRowGLM <- function(dat, Cl, ng, model, commonX, offset, Phi = 0.0, retmu = FALSE) {
    .Call('_fitgen_FitExtendedRowGLM', PACKAGE = 'fitgen', dat, Cl, ng, model, commonX, offset, Phi, retmu)
}

#' FitGLMWithNei
#'
#' Fits a General Linear Model to the requested rows of a data matrix by using as predictors those
#' included in the commonX model matrix and also those plus the columns of some rows in the data matrix which are neighbours of the current row.
#'
#' The concept of neighbourhood between rows is encoded in a nxp matrix of closeness which contains in its i-th row
#' the index of the p cases which are closest to the i-th case. The function tries to adjust two models, one
#' with and one without the added neighbours and returns its parameters and measures of goodnes-of-fit.\cr
#' It might be possible that no model can be adjusted if too many predictors are incorporated in the model matrix,
#' or even without incorporating any additional predictors. This manifests as the lack of convergence of the numerical
#' algorithms. The parameter nnei returns the maximum number of neighbours (from p and downward) that allows a stable
#' adjustment. Value 0 would indicate that only the common model could be adjusted and in this case beta1 is NULL and
#' the Wedderburn and related parameters are those of the base model.
#' Value -1 is used to indicate that not even the common model fitted. In this case values of beta0 and beta1
#' are the empty vectors and overdispersion estimators are 0.
#'
#' @param    dat     Numeric matrix of counts with n individuals/genes as rows and c studies/cases as columns
#' @param    normalized Boolean value to indicate if data are passed normalized (TRUE) or not (FALSE). If not, offset  vector is calculated inside.
#' @param    Cl      Numeric matrix of affinity with n individuals/genes as rows and the integer indexes of the p closest individuals in its p columns
#' @param    selected Boolean array of n positions indicating to which of the n rows the selected model should be fitted. Notice that calculation of
#'                    the offset vector, if requested by the normalized parameter, is done using all the individuals in the dat matrix, not only the selected ones.
#'                    Similarly, Cl must have the number of the closest neighbours, either if they are in the selected ones or not.
#' @param    model   A string with the model to fit, either "poisson","binlogit","negbin" or "binlogitw"
#' @param    commonX Partial model matrix with c rows and with the columns common to all individuals/genes. Usually generated as model.matrix(...)
#' @param    Phi_estproc Procedure to estimate the Phi parameter in the case of negbinomial model. Possible values are "none","single","common","grouped","common_edger" or "tagwise_edger".
#' @param    Phi_external Numeric vector with estimated Phi values if the estimation procedure is "common_edger" or "tagwise_edger". If a vector with correct length is passed, but estimation procedures has been set to any different to the former ones, the vector is used and the procedure is set to "common_edger". Default: empty numeric vector. 
#' @param    retmu  Boolean to indicat wheter or not the vectors of estimated means must be returned for both models. Default: FALSE
#' @return   A list of lists, each one with the following keys:
#' \itemize{
#' \item model - A string with the model used to adjust. A copy of the model parameter, useful to keep track of it when the result is included in a list, or none if selected was FALSE for that row
#' \item beta0 - A numeric vector with the value of the model parameters assuming a Poisson distribution and commonX as model matrix
#' \item Dev0  - A numeric value with the deviance of the base model
#' \item CovM0 - A numeric matrix, the covariance matrix of the maximum likelihood estimator of the model coefficients for the base model
#' \item muest0 - A numeric vector with the estimated means of the base model, or NULL if parameter retmu was FALSE
#' \item iters0 - An integer with the number of iterations until convergence of the base model
#' \item beta1 - A numeric vector with the value of the model parameters assuming a Poisson distribution and commonX plus as much as p added neighbours as model matrix.
#' \item Dev1  - A numeric value with the deviance of the extended model (commonX plus as much as p added neighbours)
#' \item CovM11 - A numeric matrix, the covariance matrix of the maximum likelihood estimator of the model coefficients for the extended model
#' \item muest1 - A numeric vector with the estimated means of the extended model, or NULL if parameter retmu was FALSE
#' \item iters1 - An integer with the number of iterations until convergence of the extended model
#' \item Bliss - The numeric value of Phi obtained using the requested Bliss-Owen method (single, common or grouped) for fits to the negative binomial model or 0.0 otherwise
#' \item Wedderburn - The numeric value of the cuasidispersion parameter of the adjusted model according to the Wedderburn estimator (1979)
#' \item Farrington - The numeric value of the cuasidispersion parameter of the adjusted model according to the Farrington estimator (1996)
#' \item Fletcher   - The numeric value of the cuasidispersion parameter of the adjusted model according to the Fletcher estimator (2012)
#' \item nnei  - An integer with the number of neigbours that still generate a valid adjusted model
#' }
#' 
#' @examples
#' # To be done
#' @export
FitGLMWithNei <- function(dat, normalized, Cl, model, selected, commonX, Phi_estproc, Phi_external = as.numeric( c()), retmu = FALSE) {
    .Call('_fitgen_FitGLMWithNei', PACKAGE = 'fitgen', dat, normalized, Cl, model, selected, commonX, Phi_estproc, Phi_external, retmu)
}

#' FitGLMInd
#'
#' Fits a General Linear Model to the requested rows of a data matrix by using as predictors those
#' included in the commonX model matrix. This is a particular case of FitGLMWithNei when no neighbours are to be considered.
#'
#' It might be possible that the model cannot be adjusted. This manifests as the lack of convergence of the numerical
#' algorithms. In such a case the vector of coefficients beta0 is returned as a 0-length vector.
#'
#' @param    dat     Numeric matrix of counts with n individuals/genes as rows and c studies/cases as columns
#' @param    normalized Boolean value to indicate if data are passed normalized (TRUE) or not (FALSE). If not, offset  vector is calculated inside.
#' @param    model   A string with the model to fit, either "poisson","binlogit","negbin" or "binlogitw"
#' @param    selected Boolean array of n positions indicating to which of the n rows the selected model should be fitted. Notice that calculation of
#'                    the offset vector, if requested by the normalized parameter, is done using all the individuals in the dat matrix, not only the selected ones.
#' @param    commonX Partial model matrix with c rows and with the columns common to all individuals/genes. Usually generated as model.matrix(...)
#' @param    Phi_estproc Procedure to estimate the Phi parameter in the case of negbinomial model. Possible values are "none","single","common","grouped","common_edger" or "tagwise_edger".
#' @param    Phi_external Numeric vector with estimated Phi values if the estimation procedure is "common_edger" or "tagwise_edger". If a vector with correct length is passed, but estimation procedures has been set to any different to the former ones, the vector is used and the procedure is set to "common_edger". Default: empty numeric vector. 
#' @param    retmu Boolean to indicate wheter or not the vector of estimated means must be returned. Default: FALSE
#' @return   A list of lists, each one with the following keys:
#' \itemize{
#' \item model - A string with the model used to adjust. A copy of the model parameter, useful to keep track of it when the result is included in a list, or none if selected was FALSE for that row
#' \item beta0 - A numeric vector with the value of the model parameters
#' \item Dev0  - A numeric value with the deviance of the base model
#' \item CovM0 - A numeric matrix, the covariance matrix of the maximum likelihood estimator of the model coefficients for the base model
#' \item muest0 - A numeric vector with the estimated means, or NULL if parameter retmu was FALSE
#' \item iters0 - An integer with the number of iterations until convergence of the base model
#' \item Bliss - The numeric value of Phi obtained using the requested Bliss-Owen method (single, common or grouped) for fits to the negative binomial model or 0.0 otherwise
#' \item Wedderburn - The numeric value of the cuasidispersion parameter of the adjusted model according to the Wedderburn estimator (1979)
#' \item Farrington - The numeric value of the cuasidispersion parameter of the adjusted model according to the Farrington estimator (1996)
#' \item Fletcher   - The numeric value of the cuasidispersion parameter of the adjusted model according to the Fletcher estimator (2012)
#' }
#' 
#' @examples
#' # To be done
#' @export
FitGLMInd <- function(dat, normalized, model, selected, commonX, Phi_estproc, Phi_external = as.numeric( c()), retmu = FALSE) {
    .Call('_fitgen_FitGLMInd', PACKAGE = 'fitgen', dat, normalized, model, selected, commonX, Phi_estproc, Phi_external, retmu)
}

#' SolveLinearSystem
#' 
#' Solves the linear system Ax=b where A is a numeric matrix of size m x n (with n>1), b is a column vector of length m
#' and x (the solution) is a column vector of length n.
#'  
#' The solution is obtained in the minimal square error sense (i.e.: sum_i |Ax_i-b|^2 is a minimum) using
#' non-explicit QR factorization of A. Therefore, the number of equations must be bigger or equal than the number
#' of unknows so m must be >= n. A is supposed to be well conditioned (i.e.: rank n). Numerical problems may arise
#' for badly conditioned A (see Error management)\cr
#'
#' WARNING: matrix A IS CHANGED inside this function. By efficiency, we have opted for NOT copying the argument in
#' a new, temporary matrix inside the function. If we want to keep your original A make a deep copy with\cr
#'                   Acopy<-matrix(A,nrow=m,ncol=n)\cr
#' before calling this function.\cr
#' 
#' After the call A will contain the upper-triangular R matrix in its upper-diagonal portion and the second-to-final
#' components of each Housholder vector v_i in the lower-diagonal part of column i. The first component is not stored
#' (no place to keep it) but it can be recovered since the Housholder vectors are of modulus 1. The Householder
#' matrix H_i can be constructed as\cr
#'                  H_i = I(m)-2*v_i'*v_i\cr
#' being I(m) the identity matrix of size n x n and v_i' the transposed of v_i.\cr
#' Finally, if the Q matrix is needed, it is\cr
#'                  Q=H(n-1) H(n-2) ... H_0 (in that order).\cr
#' Indeed, system is solved writing A*x*b as\cr
#'                  Q*R*x=b ==> R*x = Q'*b = H(n-1)*H(n-2)* ... *H_0 b\cr
#' (notice that inv(Q)=Q' and that H'(i)=H(i)\cr
#' Multiplications are done accumulatively as\cr
#'                  b(1)=H(1)*b, b(2)=H(2)*b(1), b(n-1)=H(n-1)*b(n-2), ...\cr
#' and the final triangular system\cr
#'                  R*x=b(n-1)\cr
#' is solved by back-susbtitution.
#' 
#' Error management:\cr
#' This function calls Rcpp::stop to indicate argument passing errors but it returns an empty vector to indicate lack
#' of solution because of numerical unstability, i.e.: the norm of a Housholder vector is below the tolerance. This
#' is to allow other functions try with different models if one of them cannot be adjusted. This means that the caller
#' function SHOULD check the length of the returned solution vector. 
#'
#' @param  A      Numeric matrix (system matrix)
#' @param  b      Numeric vector (independent term)
#' @param  tol    Numeric tolerance for the norm of the Housholder vector. Possitive number. Default: 1e-9
#' @return x      A numeric vector of length n with the solution\cr
#' 
#' @examples
#' m=9
#' n=6
#' A=matrix(nrow=m,ncol=n)
#' for (i in c(1:n))
#' {
#'  A[,i]=c(rep(0,i-1),c(1:(9-i+1)))
#' }
#' b=as.vector(c(m:1))
#' x=SolveLinearSystem(A,b)
#'
#' @export
SolveLinearSystem <- function(A, b, tol = 1e-9) {
    .Call('_fitgen_SolveLinearSystem', PACKAGE = 'fitgen', A, b, tol)
}

#' SolveLinearSystemWithInverse
#' 
#' Solves the linear system Ax=b where A is a square numeric matrix of size n x n (with n>1), b is a column vector of length n
#' and x (the solution) is a column vector of length n. It also returns the inverse of matrix A which, if used for estimation
#' of a linear model, is the variance/covariance matrix. Inversion is done using the QR decomposition of A used to solve the
#' linear system, so it should be faster than using simply SolveLinearSystem and invert the A matrix later.
#'  
#' The solution is obtained using QR factorization of A. A is supposed to be well conditioned (i.e.: rank n). Numerical problems
#' may arise for badly conditioned A (see Error management)\cr
#'
#' WARNING: matrix A IS CHANGED inside this function. By efficiency, we have opted for NOT copying the argument in
#' a new, temporary matrix inside the function. If you want to keep your original A make a deep copy with\cr
#'                   Acopy<-matrix(A,nrow=m,ncol=n)\cr
#' before calling this function.\cr
#' 
#' After the call A will contain the upper-triangular R matrix in its upper-diagonal portion and the second-to-final
#' components of each Housholder vector v_i in the lower-diagonal part of column i. The first component is not stored
#' (no place to keep it) but it can be recovered since the Housholder vectors are of modulus 1. The Householder
#' matrix H_i can be constructed as\cr
#'                  H_i = I(m)-2*v_i'*v_i\cr
#' being I(m) the identity matrix of size n x n and v_i' the transposed of v_i.\cr
#' Finally, if the Q matrix is needed, it is\cr
#'                  Q=H(n-1) H(n-2) ... H_0 (in that order).\cr
#' Indeed, system is solved writing A*x*b as\cr
#'                  Q*R*x=b ==> R*x = Q'*b = H(n-1)*H(n-2)* ... *H_0 b\cr
#' (notice that inv(Q)=Q' and that H'(i)=H(i)\cr
#' Multiplications are done accumulatively as\cr
#'                  b(1)=H(1)*b, b(2)=H(2)*b(1), b(n-1)=H(n-1)*b(n-2), ...\cr
#' and the final triangular system\cr
#'                  R*x=b(n-1)\cr
#' is solved by back-substitution.
#' 
#' Inverse of A is done using the QR-decomposition calculated to solve the system. Indeed, if\cr
#' A=Q*R then\cr
#' A^-1=R^-1*Q^-1.\cr
#' Being Q orthogonal, Q^-1 = Q^T, and for the upper-triangular matrix R, it can be written as\cr
#' R=D(I+N) where D is a diagonal matrix and N is nilpotent (i.e.: N^n=0). In such a case,\cr
#' R^-1=(I+N)^-1*D^-1.\cr
#' where, since D is diagonal, calculating D^-1 is trivial and a matrix lemma stablishes that, for nilpotent matrices N,\cr
#' (I+N)^-1=I+sum_p=1..(n-1) N^p\cr
#' 
#' Error management:\cr
#' This function calls Rcpp::stop to indicate argument passing errors but it returns an empty vector to indicate lack
#' of solution because of numerical unstability, i.e.: the norm of a Housholder vector is below the tolerance. This
#' is to allow other functions try with different models if one of them cannot be adjusted. This means that the caller
#' function SHOULD check the length of the returned solution vector. 
#'
#' @param  A      Numeric matrix (system matrix)
#' @param  b      Numeric vector (independent term)
#' @param  tol    Numeric tolerance for the norm of the Housholder vector. Possitive number. Default: 1e-9
#' @return A list with the following keys:
#' \itemize{
#' \item x      A numeric vector of length n with the solution\cr
#' \item Inv    A numeric matrix with the inverse of A\cr
#' }
#'
#' @export
SolveLinearSystemWithInverse <- function(A, b, tol = 1e-9) {
    .Call('_fitgen_SolveLinearSystemWithInverse', PACKAGE = 'fitgen', A, b, tol)
}

#' QRdec
#' 
#' Makes the QRdecomposition of a matrix A as A=Q*R using the Householder method.\cr
#'
#' WARNING: if you are trying to solve a linear system of the form Ax=B, DO NOT use this function\cr
#' Use instead SolveLinearSystem. Both operate with the same algorithm and are equally efficient in
#' the decomposition but this one explicitly constructs Q and R which uses more memory.\cr
#'
#' WARNING: the passed matrix IS CHANGED inside this function. By efficiency, we have opted for NOT copying
#' the argument in a new, temporary matrix inside the function. If we want to keep your original A make a 
#' deep copy with\cr
#'                   Acopy<-matrix(A,nrow=m,ncol=n)\cr
#' before calling this function.\cr
#'
#'
#' @param  A	  A (m x n) numeric matrix to be decomposed with m>=n
#' @param  tol   Numeric tolerance for the norm of the Housholder vector. Possitive number. Default: 1e-9
#' @return ret   A list with two elements
#'               ret["Q"] The orthogonal matrix Q
#'               ret["R"] The upper-triangular matrix R
#' @examples
#' m=10
#' n=8
#' A=matrix(runif(m*n),nrow=m,ncol=n)
#' Acop=matrix(A,nrow=m,ncol=n)
#' ret <- QRdec(A)
#' Arec <- ret$Q  %*% ret$R
#' error <- max(abs(Arec-Acop))
#' @export
QRdec <- function(A, tol = 1e-9) {
    .Call('_fitgen_QRdec', PACKAGE = 'fitgen', A, tol)
}

#' StGLM
#'
#' Gets a vector of observations, a type of link function, the phi parameter, the offset
#' vector and the Phi-star parameter and returns the vector of estimators beta, the value of X^2 and the final
#' values of the deviance and of the covariance matrix of the maximum likelihood estimator of the model coefficients
#'
#' Error management:\cr
#' This function calls Rcpp::stop only to signal error in pass of parameters. Errors due to numerical unstability
#' are not raised (at most, a warning is called, see parameter warn_me) but function returns an empty vector as beta value,
#' 0 for X2, sums and Dev and the empty matrix for CovM. This MUST be checked by the caller function and it is to allow it
#' to test a different, simpler model if the current one cannot be fitted.
#'
#' @param  y	  		A numeric vector of observations, length m
#' @param  X	  		A numeric matrix of predictors, size m x n
#' @param  model  		A string with the model to use. Possible values: 'Poisson', 'BinLogit', 'NegBin' or 'BinLogitW'\cr
#'                     for Possion, Binomial with logistic link, Negbinomial, and Grouped Binomial with logistic link, respectively.
#' @param  offset 		A numeric vector of offsets, length m
#' @param  warn_me     A logical value indicating if a warning must be raised in the case of numerical unstability 
#' @param  Phi    		A real value, the overdispersion parameter. Used only for Negbinomial. Default: 0.0
#' @param  retmu       A boolean value to indicate whether or not the vector of estimated means must be returned. Default: FALSE
#' @return A list with the following keys:
#' \itemize{
#' \item beta  		A numeric vector with the estimated model coefficients, or empty vector if they cannot be estimated
#' \item muest         A numeric vector with the estimated means, or NULL if parameter retmu was FALSE
#' \item X2            The statistic X^2, defined as sum((y_i-muest_i)^2/Vest_i). 0 if the model cannot be estimated
#' \item sums          The statistic sums, defined as sum((y_i-muest_i)*Vest'_i/Vest_i). 0 if the model cannot be estimated
#' \item Dev			The deviance of the model. 0 if the model cannot be estimated
#' \item CovM          Variance-covariance matrix of the maximum likelihood estimator of the model coefficients. Empty matrix if the model cannot be estimated
#' }
#' @examples
#' # To be done
#' @export
StGLM <- function(y, X, model, offset, warn_me, Phi = 0.0, retmu = FALSE) {
    .Call('_fitgen_StGLM', PACKAGE = 'fitgen', y, X, model, offset, warn_me, Phi, retmu)
}

